Smart car controller
DIT113-V22/group-15 pull request #31
Opened 2022-05-05 15:13 UTC by AlaahT

The car can be controlled by the terminal commands using the MQTT broker to be controlled manually as well as make it drive autonomously

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

2022-05-05 15:47 UTC, platisd requested changes
1. Remove and gitignore the `.DS_Store`  files
2. The new file is not built on CI
3. Why are there now two Arduino sketches?
4. Why is there commented out code in the sketch? Please either remove the code or the comments.

2022-05-05 16:04 UTC, platisd commented on .gitignore
> -## C++ stuff
You shouldn't remove this :sweat_smile:

2022-05-05 16:12 UTC, AlaahT commented
Oh, I misinterpreted your mail 😅 I thought you meant I should remove both gitignore and .DC_Store files. I'll try to change it now

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Dimitris Platis ***@***.***>
Sent: Thursday, May 5, 2022 6:04:20 PM
To: DIT113-V22/group-15 ***@***.***>
Cc: Alaa Taleb ***@***.***>; Assign ***@***.***>
Subject: Re: [DIT113-V22/group-15] Smart car controller (PR #31)


@platisd commented on this pull request.

________________________________

In .gitignore<https://github.com/DIT113-V22/group-15/pull/31#discussion_r866076369>:

> @@ -1,70 +0,0 @@

-## C++ stuff



You shouldn't remove this 😅

—
Reply to this email directly, view it on GitHub<https://github.com/DIT113-V22/group-15/pull/31#pullrequestreview-963611806>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AV26LJQADNAFX2ZHGJA2MUTVIPWQJANCNFSM5VFMXF5A>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2022-05-05 19:42 UTC, platisd commented on arduino/smartcar/SmartCarController.ino
> +#include <vector>
Why are there two arduino files?

2022-05-05 20:16 UTC, AlaahT commented
My thought was that we keep the first one since it was the first assignment and the second one is what we should use when integrating with the app. Should we just keep one of the files?

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Dimitris Platis ***@***.***>
Sent: Thursday, May 5, 2022 9:42:46 PM
To: DIT113-V22/group-15 ***@***.***>
Cc: Alaa Taleb ***@***.***>; Assign ***@***.***>
Subject: Re: [DIT113-V22/group-15] Smart car controller (PR #31)


@platisd commented on this pull request.

________________________________

In arduino/smartcar/SmartCarController.ino<https://github.com/DIT113-V22/group-15/pull/31#discussion_r866255596>:

> @@ -0,0 +1,262 @@
+#include <vector>


Why are there two arduino files?

—
Reply to this email directly, view it on GitHub<https://github.com/DIT113-V22/group-15/pull/31#pullrequestreview-963871611>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AV26LJRY2OPWL6AVAERLHNLVIQQDNANCNFSM5VFMXF5A>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2022-05-05 21:32 UTC, platisd commented
You shouldn't have any code that's not used, so please remove any dead code and make sure all code is built/verified on CI.

2022-05-05 21:35 UTC, AlaahT commented
Ok, I'll do that. Thank you so much for the feedback.

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Dimitris Platis ***@***.***>
Sent: Thursday, May 5, 2022 11:32:39 PM
To: DIT113-V22/group-15 ***@***.***>
Cc: Alaa Taleb ***@***.***>; Assign ***@***.***>
Subject: Re: [DIT113-V22/group-15] Smart car controller (PR #31)


You shouldn't have any code that's not used, so please remove any dead code and make sure all code is built/verified on CI.

—
Reply to this email directly, view it on GitHub<https://github.com/DIT113-V22/group-15/pull/31#issuecomment-1119066615>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AV26LJXNZZ2OUV3NFYTAVN3VIQ47PANCNFSM5VFMXF5A>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2022-05-06 11:02 UTC, AlaahT commented
I think I've completed all the requested changes. Is there anything I need to do?

2022-05-06 12:52 UTC, Dahlaan reviewed
Looks good but please remove file gitignore, sketch_obstacle_aavoidance.ino. Did you want to add the workflow main.yml?

2022-05-07 20:38 UTC, LabibaKararEshaba commented
Looks good.

2022-05-08 09:34 UTC, Dahlaan approved these changes

2022-05-08 14:56 UTC, merged